### ISSUE TITLE
orchestrate docker containers

### ISSUE THREAD

**Issue by olivernadj** [ngu0029/mq-app#2]
Hi Dung,
I saw hard-coded IP addresses in the code.
There are many solutions to orchestrate docker containers.

Would you mind to give it a try?

```
mq-app$ docker run -d -it --name server-app -p 5000:5000 my-server-app
35fd017cc54ef41907b3e49c36254f69d80ec79d175b992c9153c277363fb243
mq-app$ docker ps --format='table{{.Image}}\t{{.Names}}\t{{.Status}}\t{{.Ports}}'
IMAGE               NAMES               STATUS              PORTS
mq-app$ docker log
login   logout  logs    
mq-app$ docker logs server-app 
Traceback (most recent call last):
  File "./httpserver.py", line 52, in <module>
    m = main()
  File "./httpserver.py", line 49, in __init__
    self.server = http_server(self.text)
  File "./httpserver.py", line 15, in __init__
    server = HTTPServer(('172.17.0.4', 5000), SimpleHTTPRequestHandler)
  File "/usr/local/lib/python3.7/socketserver.py", line 449, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.7/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.7/socketserver.py", line 463, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address
mq-app$ 
```

**Comment by ngu0029** [comment]
Hi Oliver,

I will try it and let you know soon.

Thanks,

**Comment by ngu0029** [comment]
Hi Oliver @olivernadj 

The error in your logs might come from the fact that the assigned IP address 172.17.0.4 might have been used or not free for assignment to server-app container. (This IP addr was assigned to the server-app container on my laptop).

Anyway, I have fixed the code that support the container networking with --link option when running the containers.

Can you give it a try?

Thanks,

**Comment by ngu0029** [comment]
Hi Oliver @olivernadj 

I also support Docker Compose for building and starting the service.
You can copy the project code in the Compose directory and give it a try in your machine.

In this new code, I use the script wait-for-it.sh that lets the receiving app start running after the my-rabbitmq host and its port 5672 are ready.

Please remove any previous images (e.g. rabbitmq:3, my-sending-app, my-server-app, my-receiving-app) that you have tried before with my project code. It is because I have changed the dockerfiles for the applications with this new code supporting Docker Compose (re-building the images needed).

So now you can try with docker container linking or docker compose to start the services.

Thanks,

**Comment by olivernadj** [comment]
Let me check.

**Comment by olivernadj** [comment]
Hi Dung,
Looks OK for me.

**Comment by ngu0029** [comment]
The issue have been solved.
